In [1]:
import numpy as np

## Create a 1D NumPy array from a Python list of integers.

In [2]:
list = [1,2,3,4,5]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

## Create a 2D array with dimensions 3x3 filled with zeros.

In [3]:
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Create an array filled with ones, of shape (2, 5)

In [4]:
arr2 = np.ones((2,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Generate an array of numbers from 10 to 20 with a step size of 2.

In [5]:
arr3 = np.arange(10,21)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Create a 5x5 identity matrix using NumPy.

In [6]:
arr4 = np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generate a random array of shape (3, 3) with values between 0 and 1.

In [7]:
arr5 = np.random.rand(3,3)
arr5

array([[0.61398531, 0.31822636, 0.40259915],
       [0.89434676, 0.84339346, 0.06316171],
       [0.08162258, 0.34137775, 0.71613148]])

## Create a 3x4 array of random integers between 1 and 50.

In [8]:
arr6 = np.random.randint(1,50,size=(3,4))
arr6

array([[11, 27,  5, 33],
       [26, 10, 18, 34],
       [29, 31, 24, 29]])

## Change the shape of a 1D array into a 2D array.

In [9]:
arr7 = np.array([1,2,3,4])
print(arr7)
arr8 = arr7.reshape(2,2)
print(arr8)

[1 2 3 4]
[[1 2]
 [3 4]]


## Find the mean, median, and standard deviation of an array.

In [10]:
arr9 = np.arange(1,50)
mean = arr9.mean()
std = arr9.std()
med = np.median(arr9)
mean1 = np.mean(arr9)
std1 = np.std(arr9)
print('Mean of arr by both method', mean,mean1)

Mean of arr by both method 25.0 25.0


## Generate a random array of shape (4, 5) and find the minimum and maximum values.

In [11]:
arr10 = np.random.randint(1,10,size =(4,5))
maxi = np.max(arr10)
mini = np.min(arr10)
print(f'maximum is {maxi} and minimum is {mini}')

maximum is 9 and minimum is 1


## Add two NumPy arrays element-wise

In [12]:
arr11 = arr3+arr3
arr12 = arr8+arr8
arr12

array([[2, 4],
       [6, 8]])

## Multiply two NumPy arrays element-wise.


In [13]:
arr13 = arr3*arr3
arr14 = arr8*arr8
arr14

array([[ 1,  4],
       [ 9, 16]])

## Perform matrix multiplication between two 2D arrays

In [14]:
arr15 = np.dot(arr8,arr8)
arr15

array([[ 7, 10],
       [15, 22]])

## Create a diagonal matrix with specified values.


In [15]:
arr16 = np.diag([1,2,3])
arr16

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Extract all elements from an array that are greater than a specific value.

In [16]:
arr17=np.random.randint(1,15,size=(5,5))
print(arr17)
arr17[(arr17>4)]

[[ 6 14  4  5  4]
 [ 7  8  8  6 14]
 [ 4  4  3 12 10]
 [13 12  5  3  9]
 [ 2 12 11  2  1]]


array([ 6, 14,  5,  7,  8,  8,  6, 14, 12, 10, 13, 12,  5,  9, 12, 11])

## Replace all negative values in an array with zeros.

In [17]:
arr18 = np.array([1,2,4,-1,9,-9,8,-8])
arr18[arr18<0] = 0
arr18

array([1, 2, 4, 0, 9, 0, 8, 0])

## Flatten a multi-dimensional array into a 1D array.

In [18]:
arr19 = np.array([[1,2,3],[1,2,3]])
arr19.ndim
#So it is a 2d array
arr19.flatten()

array([1, 2, 3, 1, 2, 3])

## Stack two arrays vertically

In [19]:
arr20a = np.array([1,2,3])
arr20b = np.array([4,5,6])
arr20 = np.vstack((arr20a,arr20b))
arr20

array([[1, 2, 3],
       [4, 5, 6]])

## Stack two arrays horizontally.

In [20]:
arr21 = np.hstack((arr20a,arr20b))
arr21

array([1, 2, 3, 4, 5, 6])

## Transpose a 2D array.

In [21]:
print(arr20.ndim)
arr22 = np.transpose(arr20)
arr22

2


array([[1, 4],
       [2, 5],
       [3, 6]])

## Create an array of 10 equally spaced values between 1 and 100.

In [22]:
arr23 = np.arange(1,100,10)
arr23

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Sort a NumPy array in ascending order.

In [23]:
arr24 = np.sort(arr17,axis=-1)
arr24

array([[ 4,  4,  5,  6, 14],
       [ 6,  7,  8,  8, 14],
       [ 3,  4,  4, 10, 12],
       [ 3,  5,  9, 12, 13],
       [ 1,  2,  2, 11, 12]])

## Reverse the order of elements in an array.

In [24]:
arr25 = np.flip(arr23)
arr25 

array([91, 81, 71, 61, 51, 41, 31, 21, 11,  1])

## Use slicing to extract specific rows and columns from a 2D array.


In [25]:
#We are getting 4th element of 4th column
arr24[3][3]

12

## Find the dot product of two vectors.

In [26]:
arr26a = [1,2,3]
arr26b = [[[4],[5],[5]]]
arr26 = np.dot(arr26a,arr26b)
arr26

array([[29]])

## Calculate the sum along the rows of a 2D array.

In [27]:
arr27a = np.array([[1,2,3],[4,5,6]])
arr27 = np.sum(arr27a,axis=0)
arr27

array([5, 7, 9])

## Calculate the sum along the columns of a 2D array.

In [28]:
arr28 = np.sum(arr27a,axis=1)
arr28

array([ 6, 15])

## Generate a random permutation of an array.

In [29]:
arr29 = np.random.permutation(arr27a)
arr29

array([[4, 5, 6],
       [1, 2, 3]])

## Find the cumulative sum of elements in an array.


In [30]:
arr29.cumsum()

array([ 4,  9, 15, 16, 18, 21])

## Compute the element-wise absolute values of an array.

In [31]:
arr30=np.fabs(arr29)
arr30

array([[4., 5., 6.],
       [1., 2., 3.]])

## Use NumPy to simulate a dice roll (random integers from 1 to 6).


In [32]:
arr31 = np.random.randint(1,6)
arr31

5

## Create a boolean mask that returns True for even numbers in an array.


In [33]:
arr32 = np.array([1,2,3,4,5,6,7,8,9,10])
arr32%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## Find the index of the maximum value in an array.

In [34]:
arr6.argmax()

7

## Check if all elements in an array are non-zero.

In [35]:
np.any(arr32)

True

## Generate a 3D array of shape (2, 2, 2) with random values.


In [36]:
arr33 = np.random.rand(2,2,2)
arr33

array([[[0.86489142, 0.44583777],
        [0.66903572, 0.4947957 ]],

       [[0.24223785, 0.25401654],
        [0.53625272, 0.60071881]]])

## Normalize an array (i.e., bring the values between 0 and 1).


In [37]:
arr34 = np.array([5,6,7,8])
minim = np.min(arr34)
maxim = np.max(arr34)
nor = (arr34-minim)/(maxim-minim)
nor

array([0.        , 0.33333333, 0.66666667, 1.        ])